---
- name: configure jitsi
  hosts: all

  tasks:

  # Assume that jitsi package installation and letsencrypt setup as
  # described in
  # https://jitsi.github.io/handbook/docs/devops-guide/devops-guide-quickstart
  # have been done manually already.

  - name: set background color
    lineinfile:
      path: /usr/share/jitsi-meet/interface_config.js
      regexp: "DEFAULT_BACKGROUND:"
      line: "    DEFAULT_BACKGROUND: '#dee28f',"

  - name: configure optimal browsers
    lineinfile:
      path: /usr/share/jitsi-meet/interface_config.js
      regexp: "OPTIMAL_BROWSERS:"
      line: "    OPTIMAL_BROWSERS: ['chrome', 'chromium', 'firefox'],"
    notify:
      - restart videobridge

  - name: configure unsupported browsers
    lineinfile:
      path: /usr/share/jitsi-meet/interface_config.js
      regexp: "UNSUPPORTED_BROWSERS:"
      line: "    UNSUPPORTED_BROWSERS: [],"

  - name: disable audio level
    lineinfile:
      path: /etc/jitsi/meet/jitsi.emacs-berlin.org-config.js
      regexp: "disableAudioLevels:"
      line: "    disableAudioLevels: true,"

  - name: configure video constraints
    blockinfile:
      path: /etc/jitsi/meet/jitsi.emacs-berlin.org-config.js
      insertafter: "w3c spec-compliant video constraints"
      marker: "// {mark} ANSIBLE MANAGED BLOCK"
      block: |
        resolution: 720,
        constraints: {
          video: {
            aspectRatio: 16 / 9,
            height: {
              ideal: 720,
              max: 720,
              min: 240,
            },
          },
        },
    notify:
      - restart videobridge

  - name: require display name
    lineinfile:
      path: /etc/jitsi/meet/jitsi.emacs-berlin.org-config.js
      regexp: "requireDisplayName:"
      line: "    requireDisplayName: true,"

  - name: configure prosody auth
    replace:
      path: /etc/prosody/conf.avail/jitsi.emacs-berlin.org.cfg.lua
      after: 'VirtualHost "jitsi.emacs-berlin.org"'
      before: 'Component'
      regexp: 'authentication = "(.+)"'
      replace: 'authentication = "internal_hashed"'

  - name: configure prosody guest auth
    blockinfile:
      path: /etc/prosody/conf.avail/jitsi.emacs-berlin.org.cfg.lua
      marker: "-- {mark} ANSIBLE MANAGED BLOCK"
      block: |
        VirtualHost "guest.jitsi-meet.example.com"
            authentication = "anonymous"
            c2s_require_encryption = false

  - name: configure anonymousdomain
    lineinfile:
      path: /etc/jitsi/meet/jitsi.emacs-berlin.org-config.js
      regexp: "anonymousdomain:"
      line: "    anonymousdomain: \"guest.jitsi-meet.example.com\","

  - name: configure jicofo main domain
    lineinfile:
      path: /etc/jitsi/jicofo/sip-communicator.properties
      line: "org.jitsi.jicofo.auth.URL=XMPP:jitsi.emacs-berlin.org"

  - name: configure system.conf LimitNPROC
    lineinfile:
      path: /etc/systemd/system.conf
      line: "DefaultLimitNPROC=65000"
    notify:
      - restart videobridge

  - name: configure system.conf TasksMax
    lineinfile:
      path: /etc/systemd/system.conf
      line: "DefaultTasksMax=65000"
    notify:
      - restart videobridge

  handlers:
  - name: restart videobridge
    systemd:
      name: jitsi-videobridge2
      state: restarted
      daemon_reload: true
